cd ~

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac



force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'



# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/conda/etc/profile.d/conda.sh" ]; then
        . "/opt/conda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate wop

export EDITOR=vim

# cron
sudo service cron start
sudo update-rc.d cron enable

# aliases
alias c='clear'

bind "set completion-ignore-case on"
alias py='ipython3 --pylab'

# limpa cache, tem que ser sudo
alias lc='sync && echo 1 > /proc/sys/vm/drop_caches'
alias lswap='swapoff -a && swapon -a'
# python anaconda installer
alias ci='conda install -c conda-forge'


# rebuild crontab in case it closes
CRON_JOBS="0 11 * * * /home/sagemaker-user/work/data/GEFS/download_GEFS_AWS.sh 00 0 >> /home/sagemaker-user/work/data/GEFS/logs/g
efs.00.log 2>&1
00 10 * * * /home/sagemaker-user/work/data/GEFS/download_GEFS_AWS.sh 18 1 >> /home/sagemaker-user/work/data/GEFS/logs/gefs.12.log
 2>&1
0 9 * * * /home/sagemaker-user/work/data/GEFS/download_GEFS_AWS.sh 12 1 >> /home/sagemaker-user/work/data/GEFS/logs/gefs.18.log 2
>&1"

# Only add if not already in crontab
if ! crontab -l 2>/dev/null | grep -q "download_GEFS_AWS"; then
    (crontab -l 2>/dev/null; echo "$CRON_JOBS") | crontab -
    echo "Crontab rebuilt."
fi

