# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

cd ~

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'


# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ec2-user/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ec2-user/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ec2-user/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ec2-user/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

source /home/ec2-user/SageMaker/python_envs/week2/bin/activate

# cron
sudo systemctl start crond
sudo systemctl enable crond

#
export PATH=/home/ec2-user/SageMaker/conda/tools/bin:$PATH

# User specific aliases and functions

# aliases
alias c='clear'

bind "set completion-ignore-case on"
alias py='ipython3 --pylab'
alias spy="ource /home/ec2-user/SageMaker/python_envs/week2/bin/activate"

# limpa cache, tem que ser sudo
alias lc='sync && echo 1 > /proc/sys/vm/drop_caches'
alias lswap='swapoff -a && swapon -a'
# python anaconda installer
alias ci='conda install -c conda-forge'

# --- NOAA HPC ---
# Orion
alias orion='ssh -X rcamp@orion-login.hpc.msstate.edu'
# Orion
alias hercules='ssh -X rcamp@hercules-login.hpc.msstate.edu'
# Hera (pin+token)
alias hera='ssh -X Ricardo.Campos@hera-rsa.princeton.rdhpcs.noaa.gov'
# Niagara (pin+token)
alias niagara='ssh -X Ricardo.Campos@niagara-rsa.princeton.rdhpcs.noaa.gov'
# Ursa
alias ursa='ssh -X Ricardo.Campos@ursa-rsa.princeton.rdhpcs.noaa.gov'

# Initialize
cd /home/ec2-user/SageMaker

# Rebuild crontab if empty
if ! crontab -l 2>/dev/null | grep -q "."; then
    crontab /home/ec2-user/SageMaker/crontab
    echo "Crontab rebuilt from backup."
fi

# save crontab
alias sc='/usr/bin/crontab -l > /home/ec2-user/SageMaker/crontab'
# save bashrc
alias sb='cp -f /home/ec2-user/.bashrc /home/ec2-user/SageMaker/bashrc' 

